### ISSUE TITLE
Should not this repository be trasferred to `brico-labs` organization?

### ISSUE THREAD

**Issue by Peque** [rafacouto/OshwdemMazes#2]
The one at `brico-labs/OshwdemMazes` seems to be the "official" (the one they link [from the website](http://rules.oshwdem.org/labirinto_es)).

It feels a bit weird to have an "official" repository that is a fork and does not allow to create issues. Also, it is not easy to tell if contributors are supposed to create pull requests in one or the other repository.

Otherwise maybe it would be good to link this repository instead from the official website?

**Comment by rafacouto** [comment]
I have started this project here and it was forked to brico-labs organization to be more independent since Bricolabs decides which changes are incorporated to the Oshwdem contest. Anyway, both repositories are synced by me and I will continue to develop under this one.

You are right about the confusing indication in the readme file to create issues in the forked repository.

**Comment by rafacouto** [comment]
Links reviewed with the commit 17cbb72e15ec10a02aa9ec27d03d7cf6724f3432
